eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 400000
ribbon:
  ConnectTimeout: 60000 #400000
  ReadTimeout: 60000 #400000
  SocketTimeout: 60000 #400000