curexc:
  usd:
    cad: "1.30"
    cny: "6.70"
    hkd: "7.80"
  cad:
    cny: "5.00"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true